sudo: false
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script: 
 - npm install -g codeclimate-test-reporter
 - npm install -g istanbul
script: istanbul cover -v test/run.js 
after_script:
 - codeclimate < coverage/lcov.info
addons:
 code_climate:
  repo_token: e3b97e6049976bc7da168a4e3a137774d9f89c45412a3d48d783b5a283ee768a
matrix:
 allow_failures:
  - node_js: "0.11"